apiVersion: v1
kind: Secret
metadata:
  name: workerhub-secrets
  namespace: workerhub
type: Opaque
stringData:
  APP_KEY: base64:replace-me
  DB_USERNAME: posvirtual
  DB_PASSWORD: replace-me
  DB_ADMIN_USERNAME: posvirtual
  DB_ADMIN_PASSWORD: replace-me
  REDIS_PASSWORD: ""
  BACKOFFICE_SHARED_TOKEN: replace-me
  WORKERHUB_OPERATIONS_TOKEN: replace-me
  WORKERHUB_RUNTIME_SHARED_TOKEN: replace-me
  EPSA_SIESA_SOAP_USER: serviciosweb
  EPSA_SIESA_SOAP_PASSWORD: replace-me
  SOURCE_SQLSRV_USERNAME: posvirtual
  SOURCE_SQLSRV_PASSWORD: replace-me
